kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: {{ .Values.kafka.cluster.name }}
spec:
  kafka:
    version: {{ .Values.kafka.cluster.version }}
    authorization:
      type: simple      
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.9'
    storage:
      type: ephemeral
  zookeeper:
    storage:
      type: ephemeral
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: 10m
  entityOperator:
    topicOperator:
      watchedNamespace: "{{ .Values.namespace }}"
      resources:
        requests:
          memory: 1Gi
          cpu: 10m
    userOperator:
      watchedNamespace: "{{ .Values.namespace }}"
      resources:
        requests:
          memory: 1Gi
          cpu: 10m