kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: {{ .Values.kafka.cluster.name }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
  namespace: streaming-demo
spec:
  kafka:
    version: {{ .Values.kafka.cluster.version }}
    metadataVersion: 4.0-IV3
    authorization:
      type: simple      
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.kafka.cluster.name }}-controllers
  labels:
    strimzi.io/cluster: {{ .Values.kafka.cluster.name }}
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.kafka.cluster.name }}-brokers
  labels:
    strimzi.io/cluster: {{ .Values.kafka.cluster.name }}
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: ephemeral