apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
    labels:
        strimzi.io/cluster: {{ .Values.kafka.connect.name }}
    name: {{ .Values.kafka.connect.connector.name }}
spec:
    class: io.debezium.connector.mysql.MySqlConnector 
    tasksMax: 1
    config:          
        tasks.max: 1

        # TODO: refactor database configuration: use information from secret
        # DATABASE configuration
        database.hostname: {{ .Values.database.name }}.{{ .Values.namespace }}.svc.cluster.local
        database.port: {{ .Values.database.port }}
        database.user: {{ .Values.database.username }}
        database.password: {{ .Values.database.userpassword }}
        database.server.id: {{ .Values.database.serverid }}
        database.include.list: {{ .Values.database.database }}

        topic.creation.enable: {{ .Values.kafka.connect.topic.creation.enabled }}
        topic.creation.default.replication.factor: -1
        topic.creation.default.partitions: -1

        # -1 means it will use the default replication factor configured in the broker
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
        
        # TODO: truststore and keystore password from secret or sth. like that
        # PEM general definition
        security.protocol: SSL
        
        ssl.truststore.type: PKCS12
        ssl.truststore.location: /opt/kafka/connect-certs/{{ .Values.kafka.cluster.name }}-cluster-ca-cert/ca.p12
        ssl.truststore.password: {{ .Values.kafka.connect.connector.truststore.password }}
        
        ssl.keystore.type: PKCS12
        ssl.keystore.location: /opt/kafka/connect-certs/{{ .Values.kafka.connect.username }}/user.p12
        ssl.keystore.password: {{ .Values.kafka.connect.connector.keystore.password }}

        # debezium 2.0.x and 2.1.x
        topic.prefix: {{ .Values.kafka.connect.topic.prefix }}
        schema.history.internal.kafka.bootstrap.servers: {{ .Values.kafka.cluster.name }}-kafka-bootstrap.{{ .Values.namespace }}.svc.cluster.local:9093
        schema.history.internal.kafka.topic: {{ .Values.kafka.connect.topic.history }}
        schema.history.internal.skip.unparseable.ddl: "true"
        
        # PEM config for producer and consumer

        # producer
        schema.history.internal.producer.security.protocol: SSL
        
        schema.history.internal.producer.ssl.truststore.type: PKCS12
        schema.history.internal.producer.ssl.truststore.location: /opt/kafka/connect-certs/{{ .Values.kafka.cluster.name }}-cluster-ca-cert/ca.p12
        schema.history.internal.producer.ssl.truststore.password: {{ .Values.kafka.connect.connector.truststore.password }}

        schema.history.internal.producer.ssl.keystore.type: PKCS12
        schema.history.internal.producer.ssl.keystore.location: /opt/kafka/connect-certs/{{ .Values.kafka.connect.username }}/user.p12
        schema.history.internal.producer.ssl.keystore.password: {{ .Values.kafka.connect.connector.keystore.password }}

        # consumer
        schema.history.internal.consumer.security.protocol: SSL
        
        schema.history.internal.consumer.ssl.truststore.type: PKCS12
        schema.history.internal.consumer.ssl.truststore.location: /opt/kafka/connect-certs/{{ .Values.kafka.cluster.name }}-cluster-ca-cert/ca.p12
        schema.history.internal.consumer.ssl.truststore.password: {{ .Values.kafka.connect.connector.truststore.password }}

        schema.history.internal.consumer.ssl.keystore.type: PKCS12
        schema.history.internal.consumer.ssl.keystore.location: /opt/kafka/connect-certs/{{ .Values.kafka.connect.username }}/user.p12
        schema.history.internal.consumer.ssl.keystore.password: {{ .Values.kafka.connect.connector.keystore.password }}