apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.kafka.connect.username }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.cluster.name }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:

    # Kafka Connects internal topics used to store configuration, offsets or status
    - resource:
        type: group
        name: '*'
      operations:
        - Read
    - resource:
        type: topic
        name: '*'
      operations:
        - Create
        - Describe
        - Read
        - Write
