apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
    labels:
        strimzi.io/cluster: {{ .Values.kafka.connect.name }}
    name: {{ .Values.kafka.connect.connector.name }}
spec:
    class: io.debezium.connector.mysql.MySqlConnector 
    tasksMax: 1
    config:          
        tasks.max: 1

        # TODO: refactor database configuration: use information from secret
        # DATABASE configuration
        database.hostname: {{ .Values.database.name }}.{{ .Values.namespace }}.svc.cluster.local
        database.port: {{ .Values.database.port }}
        database.user: {{ .Values.database.username }}
        database.password: {{ .Values.database.userpassword }}
        database.server.id: {{ .Values.database.serverid }}
        database.include.list: {{ .Values.database.database }}

        topic.creation.enable: {{ .Values.kafka.connect.topic.creation.enabled }}
        topic.creation.default.replication.factor: -1
        topic.creation.default.partitions: -1

        # -1 means it will use the default replication factor configured in the broker
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
        
        # Passwords are read from Kubernetes secrets at template render time
        # truststore.password: secret "{{ .Values.kafka.cluster.name }}-cluster-ca-cert" key "ca.password"
        # keystore.password: secret "{{ .Values.kafka.connect.username }}" key "user.password"
        # PEM general definition
        security.protocol: SSL
        
        ssl.truststore.type: PKCS12
        ssl.truststore.location: /opt/kafka/connect-certs/{{ .Values.kafka.cluster.name }}-cluster-ca-cert/ca.p12
        ssl.truststore.password: {{ $truststoreSecret := lookup "v1" "Secret" .Values.namespace (printf "%s-cluster-ca-cert" .Values.kafka.cluster.name) }}{{ if $truststoreSecret }}{{ index $truststoreSecret.data "ca.password" | b64dec | quote }}{{ else }}{{ fail "Secret messaging-cluster-ca-cert not found. Please ensure the Kafka cluster CA certificate secret exists." }}{{ end }}
        
        ssl.keystore.type: PKCS12
        ssl.keystore.location: /opt/kafka/connect-certs/{{ .Values.kafka.connect.username }}/user.p12
        ssl.keystore.password: {{ $keystoreSecret := lookup "v1" "Secret" .Values.namespace .Values.kafka.connect.username }}{{ if $keystoreSecret }}{{ index $keystoreSecret.data "user.password" | b64dec | quote }}{{ else }}{{ fail (printf "Secret %s not found. Please ensure the Kafka user secret exists." .Values.kafka.connect.username) }}{{ end }}

        # debezium 2.0.x and 2.1.x
        topic.prefix: {{ .Values.kafka.connect.topic.prefix }}
        schema.history.internal.kafka.bootstrap.servers: {{ .Values.kafka.cluster.name }}-kafka-bootstrap.{{ .Values.namespace }}.svc.cluster.local:9093
        schema.history.internal.kafka.topic: {{ .Values.kafka.connect.topic.history }}
        schema.history.internal.skip.unparseable.ddl: "true"
        
        # PEM config for producer and consumer

        # producer
        schema.history.internal.producer.security.protocol: SSL
        
        schema.history.internal.producer.ssl.truststore.type: PKCS12
        schema.history.internal.producer.ssl.truststore.location: /opt/kafka/connect-certs/{{ .Values.kafka.cluster.name }}-cluster-ca-cert/ca.p12
        schema.history.internal.producer.ssl.truststore.password: {{ $truststoreSecret := lookup "v1" "Secret" .Values.namespace (printf "%s-cluster-ca-cert" .Values.kafka.cluster.name) }}{{ if $truststoreSecret }}{{ index $truststoreSecret.data "ca.password" | b64dec | quote }}{{ else }}{{ fail "Secret messaging-cluster-ca-cert not found. Please ensure the Kafka cluster CA certificate secret exists." }}{{ end }}

        schema.history.internal.producer.ssl.keystore.type: PKCS12
        schema.history.internal.producer.ssl.keystore.location: /opt/kafka/connect-certs/{{ .Values.kafka.connect.username }}/user.p12
        schema.history.internal.producer.ssl.keystore.password: {{ $keystoreSecret := lookup "v1" "Secret" .Values.namespace .Values.kafka.connect.username }}{{ if $keystoreSecret }}{{ index $keystoreSecret.data "user.password" | b64dec | quote }}{{ else }}{{ fail (printf "Secret %s not found. Please ensure the Kafka user secret exists." .Values.kafka.connect.username) }}{{ end }}

        # consumer
        schema.history.internal.consumer.security.protocol: SSL
        
        schema.history.internal.consumer.ssl.truststore.type: PKCS12
        schema.history.internal.consumer.ssl.truststore.location: /opt/kafka/connect-certs/{{ .Values.kafka.cluster.name }}-cluster-ca-cert/ca.p12
        schema.history.internal.consumer.ssl.truststore.password: {{ $truststoreSecret := lookup "v1" "Secret" .Values.namespace (printf "%s-cluster-ca-cert" .Values.kafka.cluster.name) }}{{ if $truststoreSecret }}{{ index $truststoreSecret.data "ca.password" | b64dec | quote }}{{ else }}{{ fail "Secret messaging-cluster-ca-cert not found. Please ensure the Kafka cluster CA certificate secret exists." }}{{ end }}

        schema.history.internal.consumer.ssl.keystore.type: PKCS12
        schema.history.internal.consumer.ssl.keystore.location: /opt/kafka/connect-certs/{{ .Values.kafka.connect.username }}/user.p12
        schema.history.internal.consumer.ssl.keystore.password: {{ $keystoreSecret := lookup "v1" "Secret" .Values.namespace .Values.kafka.connect.username }}{{ if $keystoreSecret }}{{ index $keystoreSecret.data "user.password" | b64dec | quote }}{{ else }}{{ fail (printf "Secret %s not found. Please ensure the Kafka user secret exists." .Values.kafka.connect.username) }}{{ end }}