kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.database.name }}
stringData:
  user: {{ .Values.database.username }}
  userPassword: {{ .Values.database.userpassword }}
  host: {{ .Values.database.name }}.{{ .Values.namespace }}.svc.cluster.local
  port: {{ .Values.database.port }}
  database: {{ .Values.database.database }}
  rootPassword: {{ .Values.database.rootpassword }}
type: Opaque
