kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.knative.job.kafka.username }}-kafka-config
stringData:
  kafka.user.name: {{ .Values.knative.job.kafka.username }}
  kafka.user.sasl.type: SCRAM-SHA-512
type: Opaque