---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.kafka.console.username }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.cluster.name }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    - resource:
        type: cluster
      operations:
      - Describe
      - DescribeConfigs
    - resource:
        type: topic
        name: "*"
        patternType: literal
      operations:
      - Read
      - Describe
      - DescribeConfigs
    - resource:
        type: group
        name: "*"
        patternType: literal
      operations:
      - Read
      - Describe